#!/bin/sh
opam switch create . ocaml-base-compiler.4.06.1 &&
eval $(opam env) &&
opam pin -yn exe . &&
opam update -y &&
opam install --deps-only exe &&
rm pp_exe/pp.exe &&
dune build @all &&
mv _build/default/pp_exe/pp.exe pp_exe/pp.exe
